### ISSUE TITLE
email aliases on committee page

### ISSUE THREAD

**Issue by s-edwards** [sigcsets/sigcse2017#14]
The committee page currently uses personal e-mails (from the CFP distributed in March).  However, over the summer we created e-mail aliases for all the positions using the sigcse2017-*@cs.vt.edu pattern.  Please update the committee page to use these aliases (feel free to leave off webmaster, if the alias isn't getting to your box correctly).

**Comment by jadudm** [comment]
I copied all the emails from the CFP.

I will go back to 2016, and use the aliases from last year, and assume they are correct for the associated roles.
