### ISSUE TITLE
Add registration info

### ISSUE THREAD

**Issue by s-edwards** [sigcsets/sigcse2017#17]
If you can pull over and insert the page with basic registration info, I can provide the new registration rates that have been approved.

**Comment by jadudm** [comment]
Send along the registration rates, and I can bring forward the pages from last year.

**Comment by s-edwards** [comment]
![image](https://cloud.githubusercontent.com/assets/1132008/17913848/266ea18a-696b-11e6-9c6d-70c652f0d157.png)

Ignore the center column--rates are on the right.

**Comment by jadudm** [comment]
Rates added in. I don't think I have dates for early/late yet, so I've removed those from the page. When I have those dates, they'll be added back in.
