### ISSUE TITLE
move sponsors menu

### ISSUE THREAD

**Issue by s-edwards** [sigcsets/sigcse2017#21]
It is currently first (leftmost) in the navbar, which should be for the CFP.  Instead, please move the sponsors & exhibitors menu down to second-to-last (just before committee).  It will still be just as visible, but won't appear more prominently than the other info.

**Comment by jadudm** [comment]
Moved.

**Comment by s-edwards** [comment]
It is still in the old position on both the production and staging sites.  Did this change not get pushed to the live site yet?
