### ISSUE TITLE
rename "registration" menu to "attendees"

### ISSUE THREAD

**Issue by s-edwards** [sigcsets/sigcse2017#22]
Michael's original proposal for the nav had "registration" and "venue" as two separate menus, but didn't include sponsors/exhibitors.  Since we need the sponsors/exhibitors at the top level, I suggest we merge the registration links with the venue links into an "attendees" menu (probably with dividers and headings to separate the menu into a "registration" part followed by a "venue" part to help break it up).

**Comment by jadudm** [comment]
I'll make this change shortly.

Neither here nor there, but it is funny how we're approaching, incrementally, the menu structure from last year...

**Comment by s-edwards** [comment]
Yeah, I noticed that ... this particular element is common on ICER and ITiCSE and many other conference sites, so I'm not sure how it ended up split in Michael's suggestion.
