### ISSUE TITLE
SRC submission instructions

### ISSUE THREAD

**Issue by tmbarnes** [sigcsets/sigcse2017#32]
On http://sigcse2017.sigcse.org/authors/studentresearchcompetition.html
Under "How do I submit my entry?"
Write your submission using the format specified above.
Convert your paper into Adobe PDF format. Refer to our [Creating Adobe PDF Documents page](http://sigcse2017.sigcse.org/authors/creating_pdf.html) for assistance.

Travel grants of up to $500 may be available for students who do not have another source of funding and are ACM student members.

**Comment by jadudm** [comment]
I took this to mean that we want PDFs, not ASCII. I have made the substitution described, and am closing the ticket.
