### ISSUE TITLE
Create Pre-Symposium Events page

### ISSUE THREAD

**Issue by tmbarnes** [sigcsets/sigcse2017#33]
Please create a page like this one http://sigcse2016.sigcse.org/authors/pre-symposiumevents.html
It should be linked under the CFP menu item, with title "Pre-symposium events"

We need the following file linked below to the words "request form (Word .docx)"
[_FORM-sigcse-pre-symposium-events-2017.docx](https://github.com/sigcsets/sigcse2017/files/486167/_FORM-sigcse-pre-symposium-events-2017.docx)
# as follows:

Date Due    September 30, 2016 (later submissions may also be considered)
Time Due    23:59 in Pago Pago, American Samoa (UTC-11h)
Submission Limits   Request to host event at Convention Center
Duration    Varies
Submission Link [EasyChair](https://easychair.org/conferences/?conf=sigcse2017) 
Notification to Authors November 1, 2016
Camera-Ready Copy   TBA

**Interested in organizing a special event at SIGCSE?**
The conference provides an opportunity for a limited number of pre-symposium events that will take place on Wednesday, March 8th, 2017. In the past, these events have included activities like workshops conducted by industry partners, computing education community roundtables, or mentoring sessions for new faculty. However, there are no specific criteria for the topics and/or format of these events. Depending on space availability, we may also be able to host evening events during the symposium.

Pre-symposium events typically are scheduled as half- or full-day sessions, and the hosting organization will be charged a fee by the symposium to cover the costs of the event including, but not limited to, incurred audio/visual charges, room set-up fees, and catering orders. Costs for each event will be determined based on your specific needs.

Please note: Pre-symposium event proposals are not peer-reviewed and are not made part of the conference proceedings. If you are looking for information about conference workshops, please see [the CFP](http://sigcse2017.sigcse.org/info/cfp.html) for more details.

**Instructions**
If you are interested in hosting a pre-symposium event at the convention center, please download and complete the request form (Word .docx) and upload it to [EasyChair](https://easychair.org/conferences/?conf=sigcse2017) in the Pre-Symposium Events Track. If you would like to host your event at the hotel, you will need to contact the hotel directly to make your own arrangements.

Application forms must be submitted by September 30, 2016 for full consideration.

**If we can accommodate your event:**

We will respond by November 1, 2016 to let you know if we can accommodate your event. More information will be provided at that time to help you with your event.

The information you provide on the request form will be posted on the SIGCSE 2016 website. SIGCSE will bill you for your room and any extra fees associated with AV or room set up.

You are responsible for managing registration and attendee fee collection for your event. The SIGCSE planning committee does not handle registration and fee collection for pre-conference and affiliated events.

You will receive information regarding whom to contact to make separate arrangements for food and beverages. The SIGCSE planning committee does not handle food and beverage orders for pre-conference and affiliated events.

**Questions**
If you have questions about anything discussed above, please contact the SIGCSE 2017 Pre-Symposium and Affiliated Events Liaison.

Rachelle Kristof Hippler
Bowling Green University - Firelands 
sigcse2017-events@cs.vt.edu

**Comment by s-edwards** [comment]
Done
