### ISSUE TITLE
posting workshop descriptions

### ISSUE THREAD

**Issue by MichelleCraig** [sigcsets/sigcse2017#42]
The link to the Google doc with the content is here:

https://docs.google.com/a/miamioh.edu/spreadsheets/d/1BXLNdUwtFcI9t_BLxq2pGZTOr8bfaiYy2xwKNHoRZlM/edit?usp=sharing

It is editable by matt_jadud@berea.edu   but when I hover over the name it shows the message "anyone holding this invitation will have access without signing in". I'm not sure if that means that you have to find the original email from Google Docs (generated when Bo added you) to be able to access the spreadsheet.

If you can't access with the URL above, email me (mcraig@cs.toronto.edu) and tell me your google account and I'll add that. Or I can download the spreadsheet and send it to you or attach it to this ticket.

**Comment by jadudm** [comment]
Ah. OK.

So, go ahead and change the sharing to "Viewable by anyone in the world," so we don't have a globally editable sheet.

My gmail account is jadudm@gmail.com. Berea is not a Google institution, and therefore the Berea address will not work for sharing.

Many thanks.

**Comment by jadudm** [comment]
It looks like it is "view only." That's good. Nevermind that part of my comment.

**Comment by jadudm** [comment]
Integrated and uploaded. Thank you *so* much for the spreadsheet. That was extremely valuable.
