### ISSUE TITLE
Typo in name of workshop presenter in draft-program.pdf

### ISSUE THREAD

**Issue by MichelleCraig** [sigcsets/sigcse2017#51]
The second presenter of the workshop, "How to Integrate (Inter)Active Learning into Large Classes" should be "Andreas Seitz" but is listed as ",reas Seitz" in the posted file, http://sigcse2017.sigcse.org/docs/sigcse2017-draft-program.pdf  

This person's name is correct in the workshop information file at http://sigcse2017.sigcse.org/attendees/workshops.html

Matt,
  I'm not even sure you are/were responsible for generating that draft program or if someone else gave you the pdf version to post. If it is the latter, just close this issue and tell me who I should be reporting this error to. Even if it is the former, this issue is a low priority. I told the presenter I would report it but that there may be other priority tasks. 
-- Michelle

**Comment by jadudm** [comment]
I don't have control over the PDF. I've passed this on to Steve.
