### ISSUE TITLE
Revise title of workshop #408 

### ISSUE THREAD

**Issue by MichelleCraig** [sigcsets/sigcse2017#52]
The title of workshop #408 should be
" How to Integrate Interactive Learning into Large Classes". It is incorrect in http://sigcse2017.sigcse.org/attendees/workshops.html because it was incorrect in the spreadsheet Bo and I provided. I'll go fix the spreadsheet after filing this issue but I can't fix the website copy.

**Comment by s-edwards** [comment]
Fixed.

**Comment by s-edwards** [comment]
Note: when editing, jekyll needs the CSV to be in UTF-8, but editing with Excel will leave the CSV in iso-8859-1.  Character encoding conversion is necessary to preserve unicode characters in the file.  Be careful (hope I haven't messed it up myself!).
